# версия docker-compose
version: '2.29.7'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./handbook_materials/handbook_materials/.env
  web:
    build: .
    restart: always
    ports:
     - "8000:8000"
    # "зависит от", 
    depends_on:
      - db
    env_file:
      - ./handbook_materials/handbook_materials/.env
