# Generated by Django 5.1.3 on 2024-11-19 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сategory',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='сategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='materials.сategory'),
        ),
    ]
